-- Logger (bindings/logger.cpp) and the removed 2.x globals (removed_globals.cpp).

test("levels by name and by 2.x's numbers", function()
    Logger.setLevel("warn")
    expect_eq(Logger.getLevel(), "warn", "warn")
    Logger.setLevel(0)
    expect_eq(Logger.getLevel(), "debug", "0 is debug")
    Logger.setLevel(4)
    expect_eq(Logger.getLevel(), "critical", "4 is critical")
    Logger.setLevel(5)
    expect_eq(Logger.getLevel(), "off", "5 is off")
    expect_error("bad argument #1 to 'setLevel' (level must be", function() Logger.setLevel("loud") end)
    expect_error("bad argument #1 to 'setLevel' (value 6 out of range [0, 5])", function() Logger.setLevel(6) end)
    Logger.setLevel("info")
end)

test("messages", function()
    Logger.info("an info message")
    Logger.warn(42)
    expect_error("bad argument #1 to 'error' (string expected, got table)", function() Logger.error({}) end)
end)

test("removed 2.x globals explain what replaces them", function()
    expect_error("MySQL was removed in 3.0: use require \"luasql.mysql\" (see docs/MIGRATION-v3.md#mysql)",
        function() return MySQL.createConnection end)
    expect_error("SQLite was removed in 3.0", function() SQLite.openDatabase("x.db") end)
    expect_error("Remote was removed in 3.0: use require \"http\"", function() Remote.fetch("x") end)
    expect_error("JSON was removed in 3.0: use require \"cjson\"", function() return JSON.encode end)
    expect_error("Thread was removed in 3.0", function() Thread() end)
    expect_error("dbg was removed in 3.0", function() dbg() end)
    expect_error("SqLite was removed in 3.0", function() SqLite.x = 1 end)
    expect_eq(getmetatable(MySQL), false, "the metatable is protected")
end)
