-- Player (bindings/player.cpp) against the recording fake server.

local p = fake.connect("Alice")

test("class basics", function()
    expect_eq(Player.type(), "Player", "Player.type()")
    expect_eq(p:getType(), "Player", "getType")
    expect_eq(p.id, 0, "id")
    expect_eq(p:getID(), 0, "getID")
    expect_eq(p.valid, true, "valid")
    expect_eq(Player.findByID(0), p, "findByID")
    expect_eq(Player.findByID(99), nil, "findByID of a free id")
    expect_eq(Player.findByID(-1), nil, "findByID(-1)")
    expect_eq(Player.count(), 1, "count")
    expect_eq(tostring(p), "Player(0)", "tostring")
end)

test("messages are sent with a %s format", function()
    expect_eq(p:msg("hello %n %s"), true, "msg")
    expect_call('SendClientMessage(0, 4294967295, "hello %n %s")')
    p:msg("red", 0xFF0000FF)
    expect_call('SendClientMessage(0, 4278190335, "red")')
    p:msg("negative colour", -1)
    expect_call('SendClientMessage(0, 4294967295, "negative colour")')
    p:announce("big", 3)
    expect_call('SendGameMessage(0, 3, "big")')
    p:announce("default type")
    expect_call('SendGameMessage(0, 0, "default type")')
end)

test("numeric properties", function()
    p.health = 50
    expect_call("SetPlayerHealth(0, 50)")
    fake.ret("GetPlayerHealth", 75.5)
    expect_eq(p.health, 75.5, "health")
    p.armour = 1000 / 4
    expect_call("SetPlayerArmour(0, 250)")
    p.world = 2
    expect_call("SetPlayerWorld(0, 2)")
    fake.ret("GetPlayerWorld", 7)
    expect_eq(p.world, 7, "world")
    p.secondaryWorld = 3
    expect_call("SetPlayerSecondaryWorld(0, 3)")
    p.team = 4
    expect_call("SetPlayerTeam(0, 4)")
    p.skin = 5
    expect_call("SetPlayerSkin(0, 5)")
    p.cash = -100
    expect_call("SetPlayerMoney(0, -100)")
    p.score = 10
    expect_call("SetPlayerScore(0, 10)")
    p.wantedLevel = 6
    expect_call("SetPlayerWantedLevel(0, 6)")
    p.immunity = 0xFFFF
    expect_call("SetPlayerImmunityFlags(0, 65535)")
    p.color = -16776961
    expect_call("SetPlayerColour(0, 4278190335)")
    p.weaponSlot = 2
    expect_call("SetPlayerWeaponSlot(0, 2)")
    p.angle = 1.5
    expect_call("SetPlayerHeading(0, 1.5)")
    p.drunkHandling = 3
    expect_call("SetPlayerDrunkHandling(0, 3)")
    p.drunkVisuals = 255
    expect_call("SetPlayerDrunkVisuals(0, 255)")
    expect_error("bad value for 'drunkVisuals' (value 256 out of range [0, 255])",
        function() p.drunkVisuals = 256 end)
    p.admin = true
    expect_call("SetPlayerAdmin(0, 1)")
    fake.ret("IsPlayerAdmin", 1)
    expect_eq(p.admin, true, "admin")
    fake.ret("IsPlayerAdmin", 0)
    expect_eq(p.admin, false, "admin is false, not 0")
end)

test("bad values raise errors that name the property or method", function()
    expect_error("player.lua:", function() p.health = "full" end)
    expect_error("bad value for 'health' (number expected, got string)", function() p.health = "full" end)
    expect_error("bad value for 'world' (number has no integer representation)", function() p.world = 1.5 end)
    expect_error("bad value for 'admin' (boolean expected, got number)", function() p.admin = 1 end)
    expect_error("bad argument #1 to 'setWeapon' (integer expected, got string)",
        function() p:setWeapon("m4", 100) end)
    expect_error("bad argument #2 to 'setWeapon' (integer expected, got no value)",
        function() p:setWeapon(26) end)
end)

test("server errors", function()
    fake.error("SetPlayerWorld", 4)
    expect_error("'world' failed: argument out of bounds", function() p.world = -5 end)
    fake.error("SetPlayerWorld", 0)
    fake.error("PutPlayerInVehicle", 8)
    local vehicle = test_create_vehicle()
    expect_eq(p:setVehicle(vehicle), false, "a refused request returns false")
    fake.error("PutPlayerInVehicle", 0)
    expect_eq(p:setVehicle(vehicle, 1), true, "setVehicle")
    expect_call("PutPlayerInVehicle(0, " .. vehicle.id .. ", 1, 1, 1)")
    fake.error("GetPlayerOption", 4)
    expect_error("'getOption' failed: argument out of bounds", function() p:getOption(99) end)
    fake.error("GetPlayerOption", 0)
    fake.remove("KillPlayer")
    expect_error("KillPlayer is not supported by this server version", function() p:kill() end)
end)

test("name is read from the server and checked when set", function()
    expect_eq(p.name, "Alice", "name")
    p.name = "Bob"
    expect_call('SetPlayerName(0, "Bob")')
    expect_eq(p.name, "Bob", "the new name, not a cached one")
    expect_error("'name' failed: invalid name", function() p.name = string.rep("x", 100) end)
end)

test("text properties check the server's result", function()
    fake.text("GetPlayerIP", "1.2.3.4")
    expect_eq(p.ip, "1.2.3.4", "ip")
    expect_eq(p:getIP(), "1.2.3.4", "getIP")
    fake.text("GetPlayerUID", "uid-1")
    expect_eq(p.uid, "uid-1", "uid")
    fake.text("GetPlayerUID2", "uid-2")
    expect_eq(p:getUID2(), "uid-2", "getUID2")
    fake.error("GetPlayerUID", 1)
    expect_error("'uid' failed: no such entity", function() return p.uid end)
    fake.error("GetPlayerUID", 0)
end)

test("read-only values", function()
    fake.ret("GetPlayerKey", 1234)
    expect_eq(p.key, 1234, "key")
    fake.ret("GetPlayerState", 3)
    expect_eq(p.state, PlayerState.driver, "state")
    expect_eq(p:getState(), 3, "getState")
    expect_eq(p.online, true, "online")
    expect_eq(p:isOnline(), true, "isOnline")
    fake.ret("IsPlayerSpawned", 1)
    expect_eq(p.spawned, true, "spawned")
    expect_eq(p.typing, false, "typing")
    fake.ret("GetPlayerPing", 42)
    expect_eq(p.ping, 42, "ping")
    fake.ret("GetPlayerFPS", 59.5)
    expect_eq(p.fps, 59.5, "fps")
    fake.ret("GetPlayerWeaponAmmo", 30)
    expect_eq(p.ammo, 30, "ammo (v1's always raised an error)")
    fake.ret("GetPlayerWeapon", 26)
    expect_eq(p.weapon, 26, "weapon")
    fake.ret("GetPlayerInVehicleStatus", 3)
    expect_eq(p.vehicleStatus, PlayerVehicle.inside, "vehicleStatus")
    fake.ret("IsCameraLocked", 1)
    expect_eq(p.cameraLocked, true, "cameraLocked")
    fake.ret("GetPlayerDrunkVisuals", 7)
    expect_eq(p:getDrunkVisuals(), 7, "getDrunkVisuals")
    fake.ret("GetNetworkStatistics", 0.25)
    expect_eq(p:getNetworkStatistics(NetworkStatistics.packetLossTotal), 0.25, "getNetworkStatistics")
    expect_call("GetNetworkStatistics(0, 16)")
end)

test("vectors", function()
    fake.out("GetPlayerPosition", { 1.5, -2, 3 })
    expect_vec(p.position, 1.5, -2, 3, "position")
    p.position = { 4, 5, 6 }
    expect_call("SetPlayerPosition(0, 4, 5, 6)")
    expect_error("bad value for 'position' (element 3 must be a number, got nil)",
        function() p.position = { 1, 2 } end)
    fake.out("GetPlayerSpeed", { 0.5, 0, 0 })
    expect_vec(p.speed, 0.5, 0, 0, "speed")
    p:addSpeed(1, 2, 3)
    expect_call("AddPlayerSpeed(0, 1, 2, 3)")
    fake.out("GetPlayerAimPosition", { 7, 8, 9 })
    expect_vec(p.aimPosition, 7, 8, 9, "aimPosition")
end)

test("vehicle and spectateTarget accept nil", function()
    expect_eq(p.vehicle, nil, "not in a vehicle")
    fake.clear()
    p.vehicle = nil
    expect_calls({ "GetPlayerVehicleId(0)" })
    local vehicle = test_create_vehicle()
    fake.ret("GetPlayerVehicleId", vehicle.id)
    expect_eq(p.vehicle, vehicle, "the vehicle's handle")
    p.vehicle = nil
    expect_call("RemovePlayerFromVehicle(0)")
    p.vehicle = vehicle
    expect_call("PutPlayerInVehicle(0, " .. vehicle.id .. ", 0, 1, 1)")
    expect_error("bad value for 'vehicle' (Vehicle expected, got Player)", function() p.vehicle = p end)
    fake.ret("GetPlayerVehicleId", 0)

    local q = fake.connect("Carol")
    p.spectateTarget = q
    expect_call("SetPlayerSpectateTarget(0, " .. q.id .. ")")
    p.spectateTarget = nil
    expect_call("SetPlayerSpectateTarget(0, -1)")
    fake.ret("GetPlayerSpectateTarget", -1)
    expect_eq(p.spectateTarget, nil, "no target")
    fake.ret("GetPlayerSpectateTarget", q.id)
    expect_eq(p.spectateTarget, q, "target")
    fake.disconnect(q.id)
end)

test("methods", function()
    p:setWeapon(26, 500)
    expect_call("SetPlayerWeapon(0, 26, 500)")
    p:giveWeapon(19, 10)
    expect_call("GivePlayerWeapon(0, 19, 10)")
    p:removeWeapon(19)
    expect_call("RemovePlayerWeapon(0, 19)")
    p:disarm()
    expect_call("RemoveAllWeapons(0)")
    p:setAlpha(100)
    expect_call("SetPlayerAlpha(0, 100, 0)")
    p:setAlpha(100, 500)
    expect_call("SetPlayerAlpha(0, 100, 500)")
    p:setOption(PlayerOption.controllable, false)
    expect_call("SetPlayerOption(0, 0, 0)")
    fake.ret("GetPlayerOption", 1)
    expect_eq(p:getOption(PlayerOption.widescreen), true, "getOption")
    p:setAnimation(5)
    expect_call("SetPlayerAnimation(0, 0, 5)")
    p:setAnimation(2, 5)
    expect_call("SetPlayerAnimation(0, 2, 5)")
    p:setCamera({ 1, 2, 3 }, { 4, 5, 6 })
    expect_call("SetCameraPosition(0, 1, 2, 3, 4, 5, 6)")
    p:setCamera(1, 2, 3, 4, 5, 6)
    expect_call("SetCameraPosition(0, 1, 2, 3, 4, 5, 6)")
    p:interpolateCamLookAt({ 1, 2, 3 }, 1000)
    expect_call("InterpolateCameraLookAt(0, 1, 2, 3, 1000)")
    p:restoreCamera()
    expect_call("RestoreCamera(0)")
    p:forceSpawn()
    expect_call("ForcePlayerSpawn(0)")
    p:selectClass()
    expect_call("ForcePlayerSelect(0)")
    p:eject()
    expect_call("RemovePlayerFromVehicle(0)")
    p:setDrunkHandling(10)
    expect_call("SetPlayerDrunkHandling(0, 10)")
    p:giveMoney(5)
    expect_call("GivePlayerMoney(0, 5)")
    fake.ret("GetPlayerAmmoAtSlot", 12)
    expect_eq(p:getAmmoAtSlot(3), 12, "getAmmoAtSlot")
    p:getModules()
    expect_call("GetPlayerModuleList(0)")
end)

test("sounds", function()
    fake.ret("GetPlayerUniqueWorld", 9)
    expect_eq(p:playSound(50), true, "played")
    expect_call("PlaySound(9, 50, nan, nan, nan)")
    p:playSound3D(51, { 1, 2, 3 })
    expect_call("PlaySound(9, 51, 1, 2, 3)")
    fake.out("GetPlayerPosition", { 4, 5, 6 })
    p:playSound3D(52)
    expect_call("PlaySound(9, 52, 4, 5, 6)")
end)

test("other players as arguments", function()
    local q = fake.connect("Dave")
    fake.ret("IsPlayerStreamedForPlayer", 1)
    expect_eq(p:isPlayerStreamed(q), true, "isPlayerStreamed")
    expect_call("IsPlayerStreamedForPlayer(0, " .. q.id .. ")")
    p:set3DArrowToPlayer(q, true)
    expect_call("SetPlayer3DArrowForPlayer(0, " .. q.id .. ", 1)")
    expect_error("bad argument #1 to 'set3DArrowToPlayer' (Player expected, got nil)",
        function() p:set3DArrowToPlayer(nil, true) end)
    fake.disconnect(q.id)
    expect_error("player no longer exists", function() p:isPlayerStreamed(q) end)
end)

test("redirect passes the current name", function()
    p:redirect("127.0.0.1", 8192)
    expect_call('RedirectPlayerToServer(0, "127.0.0.1", 8192, "Bob", "", "")')
    p:redirect("127.0.0.1", 8192, "secret", "mine")
    expect_call('RedirectPlayerToServer(0, "127.0.0.1", 8192, "Bob", "secret", "mine")')
end)

test("static functions", function()
    local q = fake.connect("Eve")
    Player.msgAll("hi all")
    expect_calls({ 'SendClientMessage(0, 4294967295, "hi all")',
                   'SendClientMessage(' .. q.id .. ', 4294967295, "hi all")' })
    fake.clear()
    Player.announceAll("big", 1)
    expect_eq(#fake.calls(), 2, "one announcement per player")
    fake.ret("IsPlayerSpawned", 0)
    expect_eq(next(Player.getActive(true)), nil, "nobody spawned")
    local all = Player.getActive()
    expect_eq(all[0], p, "getActive()[0]")
    expect_eq(all[q.id], q, "getActive()[q.id]")
    fake.ret("IsPlayerSpawned", 1)
    expect_eq(Player.getActive(true)[q.id], q, "getActive(true)")
    fake.ret("GetPlayerIdFromName", q.id)
    expect_eq(Player.findByName("Eve"), q, "findByName")
    fake.ret("GetPlayerIdFromName", -1)
    expect_eq(Player.findByName("nobody"), nil, "findByName of nobody")
    fake.disconnect(q.id)
end)

test("kick: the disconnect happens inside the call and the handle dies", function()
    local q = fake.connect("Mallory")
    local reason
    Event.bind("onPlayerDisconnect", function(player, r)
        if player == q then reason = r end
    end)
    q:kick()
    expect_eq(reason, DisconnectReason.kick, "disconnect reason")
    expect_eq(q.valid, false, "valid after kick")
    expect_error("player no longer exists", function() return q.health end)
    expect_eq(tostring(q), "Player(1, no longer exists)", "tostring")
end)
