-- Server, Map, Radio, Weapon, Blip and Sound (bindings/server.cpp).

local p = fake.connect("Alice")

test("Server text settings: methods and properties", function()
    expect_eq(Server.type(), "Server", "type")
    fake.text("GetServerName", "My Server")
    expect_eq(Server.name, "My Server", "name")
    expect_eq(Server.getName(), "My Server", "getName")
    Server.name = "Renamed"
    expect_call('SetServerName("Renamed")')
    Server.setName("Again")
    expect_call('SetServerName("Again")')
    Server.gamemode = "TDM"
    expect_call('SetGameModeText("TDM")')
    fake.text("GetGameModeText", "DM")
    expect_eq(Server.getGame(), "DM", "getGame")
    Server.setPassword("secret")
    expect_call('SetServerPassword("secret")')
    Server.maxPlayers = 50
    expect_call("SetMaxPlayers(50)")
    expect_eq(Server.getMaxPlayers(), 100, "getMaxPlayers")
    expect_error("bad value for 'maxPlayers' (value -1 out of range [0, 4294967295])",
        function() Server.maxPlayers = -1 end)
end)

test("options and settings", function()
    Server.setOption(ServerOption.friendlyFire, true)
    expect_call("SetServerOption(5, 1)")
    fake.ret("GetServerOption", 0)
    expect_eq(Server.getOption(ServerOption.friendlyFire), false, "getOption")
    local settings = Server.getSettings()
    expect_eq(settings.maxPlayers, 0, "settings.maxPlayers")
    expect_eq(settings.serverName, "", "settings.serverName")
    expect_eq(type(settings.serverPassword), "string", "settings.serverPassword")
end)

test("addClass: the three forms, weapons from the right arguments", function()
    fake.ret("AddPlayerClass", 3)
    expect_eq(Server.addClass(1, 0xFF0000FF, 5, 1, 2, 3, 0.5, 26, 100), 3, "class id")
    expect_call("AddPlayerClass(1, 4278190335, 5, 1, 2, 3, 0.5, 26, 100, 0, 0, 0, 0)")
    Server.addClass(1, -1, 5, { 1, 2, 3 }, 0.5, 26, 100, 19, 5)
    expect_call("AddPlayerClass(1, 4294967295, 5, 1, 2, 3, 0.5, 26, 100, 19, 5, 0, 0)")
    Server.addClass(1, -1, 5, { 1, 2, 3, 0.25 }, 26, 100)
    expect_call("AddPlayerClass(1, 4294967295, 5, 1, 2, 3, 0.25, 26, 100, 0, 0, 0, 0)")
    Server.addClass(2, 0, 6, { 1, 2, 3 }, 1)
    expect_call("AddPlayerClass(2, 0, 6, 1, 2, 3, 1, 0, 0, 0, 0, 0, 0)")
    fake.ret("AddPlayerClass", -1)
    fake.error("AddPlayerClass", 6)
    expect_error("'addClass' failed: pool exhausted", function() Server.addClass(1, 0, 0, 0, 0, 0, 0) end)
    fake.error("AddPlayerClass", 0)
end)

test("class selection camera", function()
    Server.setClassPosition(1, 2, 3)
    expect_call("SetSpawnPlayerPosition(1, 2, 3)")
    Server.setClassCameraPosition({ 4, 5, 6 })
    expect_call("SetSpawnCameraPosition(4, 5, 6)")
    Server.setClassCameraLook(7, 8, 9)
    expect_call("SetSpawnCameraLookAt(7, 8, 9)")
end)

test("IP bans take strings", function()
    fake.ret("IsIPBanned", 0)
    expect_eq(Server.banIP("1.2.3.4"), true, "banIP")
    expect_call('BanIP("1.2.3.4")')
    fake.ret("IsIPBanned", 1)
    expect_eq(Server.banIP("1.2.3.4"), false, "already banned")
    expect_eq(Server.isIPBanned("1.2.3.4"), true, "isIPBanned")
    fake.ret("UnbanIP", 1)
    expect_eq(Server.unbanIP("1.2.3.4"), true, "unbanIP")
    expect_call('UnbanIP("1.2.3.4")')
end)

test("explosions", function()
    Server.createExplosion(0, 1, { 1, 2, 3 })
    expect_call("CreateExplosion(0, 1, 1, 2, 3, -1, 0)")
    Server.createExplosion(0, 1, 1, 2, 3, p, true)
    expect_call("CreateExplosion(0, 1, 1, 2, 3, 0, 1)")
end)

test("skin and weapon names", function()
    expect_eq(Server.getSkinName(0), "Tommy Vercetti", "getSkinName(0)")
    expect_eq(Server.getSkinName(8), nil, "getSkinName(8): no such skin")
    expect_eq(Server.getSkinName(1000), nil, "getSkinName(1000)")
    expect_eq(Server.getSkinID("cop"), 1, "getSkinID cop")
    expect_eq(Server.getSkinID("Army"), 4, "getSkinID army")
    expect_eq(Server.getSkinID(""), -1, "getSkinID of nothing")
    expect_eq(Server.getSkinID("é"), -1, "getSkinID of a non-ASCII name")
    expect_eq(Weapon.getName(26), "M4", "Weapon.getName")
    expect_eq(Weapon.getName(1000), "Unknown", "Weapon.getName unknown")
    expect_eq(Weapon.getID("m4"), 26, "Weapon.getID")
    expect_eq(Weapon.getID("Uzi"), 23, "Weapon.getID uzi")
    expect_eq(Weapon.getID(""), 0, "Weapon.getID empty")
end)

test("world properties", function()
    Server.hour = 12
    expect_call("SetHour(12)")
    fake.ret("GetMinute", 30)
    expect_eq(Server.minute, 30, "minute")
    Server.weather = 4
    expect_call("SetWeather(4)")
    Server.timeRate = 1000
    expect_call("SetTimeRate(1000)")
    Server.gravity = 0.008
    expect_call("SetGravity(0.008)")
    Server.waterLevel = 6
    expect_call("SetWaterLevel(6)")
    Server.gameSpeed = 1
    expect_call("SetGameSpeed(1)")
    Server.flightAltitude = 100
    expect_call("SetMaximumFlightAltitude(100)")
    Server.vehicleRespawnHeight = -10
    expect_call("SetVehiclesForcedRespawnHeight(-10)")
    Server.killDelay = 5
    expect_call("SetKillCommandDelay(5)")
    Server.fallTimer = 500
    expect_call("SetFallTimer(500)")
    expect_error("bad value for 'fallTimer' (value 70000 out of range [0, 65535])",
        function() Server.fallTimer = 70000 end)
end)

test("wastedSettings: partial tables keep the other fields", function()
    fake.out("GetWastedSettings", { 1000, 2000, 1.5, 2.5, 0xFF, 3000, 4000 })
    local w = Server.wastedSettings
    expect_eq(w.deathTimer, 1000, "deathTimer")
    expect_eq(w.fadeOutSpeed, 2.5, "fadeOutSpeed")
    expect_eq(w.corpseFadeTime, 4000, "corpseFadeTime")
    Server.wastedSettings = { deathTimer = 5000, fadeInSpeed = 0.5 }
    expect_call("SetWastedSettings(5000, 2000, 0.5, 2.5, 255, 3000, 4000)")
end)

test("shutdown", function()
    Server.shutdown()
    expect_call("ShutdownServer()")
end)

test("Map", function()
    Map.setBounds(100, -100, 200, -200)
    expect_call("SetWorldBounds(100, -100, 200, -200)")
    fake.out("GetWorldBounds", { 1, 2, 3, 4 })
    local b = Map.getBounds()
    expect_eq(b.max_x, 1, "max_x")
    expect_eq(b.min_y, 4, "min_y")
    Map.hideObject(300, 1.24, -2, 3)
    expect_call("HideMapObject(300, 12, -20, 30)")
    Map.hideObject(300, 1.26, -2.06, 0.04)
    expect_call("HideMapObject(300, 13, -21, 0)")
    Map.hideObjectRaw(300, 12, -20, 30)
    expect_call("HideMapObject(300, 12, -20, 30)")
    Map.showMapObject(300, { 1.2, -2, 3 })
    expect_call("ShowMapObject(300, 12, -20, 30)")
    Map.showObject(300, 0, 0, 0)
    expect_call("ShowMapObject(300, 0, 0, 0)")
    Map.showAllObjects()
    expect_call("ShowAllMapObjects()")
    expect_error("coordinate out of range", function() Map.hideObject(300, 5000, 0, 0) end)
    expect_eq(Map.getDistrictName(0, 0), "Leaf Links", "district")
    expect_eq(Map.getDistrictName({ -1000, 1000, 10 }), "Downtown Vice City", "district from a table")
    expect_eq(Map.getDistrictName(5000, 5000), "Vice City", "outside every district")
end)

test("Radio", function()
    expect_eq(Radio.createStream("Wave", "http://x/"), true, "createStream")
    expect_call('AddRadioStream(-1, "Wave", "http://x/", 1)')
    Radio.createStream(5, "Flash", "http://y/", false)
    expect_call('AddRadioStream(5, "Flash", "http://y/", 0)')
    fake.error("AddRadioStream", 4)
    expect_error("'createStream' failed: argument out of bounds",
        function() Radio.createStream(99, "x", "y") end)
    fake.error("AddRadioStream", 0)
    Radio.destroyStream(5)
    expect_call("RemoveRadioStream(5)")
end)

test("Weapon data", function()
    fake.ret("GetWeaponDataValue", 2.5)
    expect_eq(Weapon.data(26, 1), 2.5, "read")
    expect_eq(Weapon.data(26, 1, 3.5), nil, "write returns nothing")
    expect_call("SetWeaponDataValue(26, 1, 3.5)")
    fake.ret("IsWeaponDataValueModified", 1)
    expect_eq(Weapon.isFieldModified(26, 1), true, "isFieldModified")
    Weapon.resetField(26, 1)
    expect_call("ResetWeaponDataValue(26, 1)")
    Weapon.reset(26)
    expect_call("ResetWeaponData(26)")
    Weapon.resetAll()
    expect_call("ResetAllWeaponData()")
end)

test("Blip: create returns a handle; destroy and getInfo take a handle or an id", function()
    local a = Blip.create(0, { 1, 2, 3 }, 2, 0xFF0000FF, 5)
    expect_call("CreateCoordBlip(-1, 0, 1, 2, 3, 2, 4278190335, 5)")
    expect_eq(tostring(a), "Blip(0)", "handle")
    local b = Blip.create(7, 0, { 1, 2, 3 }, 2, 0, 5)
    expect_call("CreateCoordBlip(7, 0, 1, 2, 3, 2, 0, 5)")
    local c = Blip.create(0, 1, 2, 3, 2, 0, 5)
    expect_call("CreateCoordBlip(-1, 0, 1, 2, 3, 2, 0, 5)")
    local d = Blip.create(9, 0, 1, 2, 3, 2, 0, 5)
    expect_call("CreateCoordBlip(9, 0, 1, 2, 3, 2, 0, 5)")
    fake.out("GetCoordBlipInfo", { 3, 1, 2, 3, 2, 255, 5 })
    local info = a:getInfo()
    expect_eq(info.world, 3, "info.world")
    expect_vec(info.position, 1, 2, 3, "info.position")
    expect_eq(info.color, 255, "info.color")
    expect_eq(Blip.getInfo(a).sprite, 5, "Blip.getInfo(handle)")
    expect_eq(Blip.getInfo(a.id).sprite, 5, "Blip.getInfo(id)")
    expect_eq(a:destroy(), true, "a:destroy()")
    expect_eq(a.valid, false, "a is gone")
    expect_eq(Blip.destroy(b), true, "Blip.destroy(handle)")
    local c_id = c.id
    expect_eq(Blip.destroy(c_id), true, "Blip.destroy(id)")
    expect_eq(c.valid, false, "c is gone")
    expect_eq(Blip.destroy(c_id), false, "no such blip")
    d:destroy()
    expect_eq(Blip.count(), 0, "count")
end)

test("Sound.play: every v1 form", function()
    Sound.play(50)
    expect_call("PlaySound(0, 50, nan, nan, nan)")
    Sound.play(50, { 1, 2, 3 })
    expect_call("PlaySound(0, 50, 1, 2, 3)")
    Sound.play(2, 50)
    expect_call("PlaySound(2, 50, nan, nan, nan)")
    Sound.play(2, 50, { 1, 2, 3 })
    expect_call("PlaySound(2, 50, 1, 2, 3)")
    Sound.play(50, 1, 2, 3)
    expect_call("PlaySound(0, 50, 1, 2, 3)")
    Sound.play(2, 50, 1, 2, 3)
    expect_call("PlaySound(2, 50, 1, 2, 3)")
end)

test("wastedSettings reads its table without metamethods", function()
    local touched = false
    Server.wastedSettings = setmetatable({ deathTimer = 1 }, { __index = function() touched = true end })
    expect_eq(touched, false, "__index ran inside the binding")
end)
