-- Stream (bindings/stream.cpp): client script data.

local p = fake.connect("Alice")

test("write then read back", function()
    local s = Stream()
    s:writeByte(255)
    s:writeByte(-1)
    s:writeNumber(-2)
    s:writeNumber(0xFFFFFFFF)
    s:writeFloat(1.5)
    s:writeString("hi")
    expect_eq(s.size, 1 + 1 + 4 + 4 + 4 + 2 + 2, "size")
    expect_eq(s:readByte(), 255, "byte")
    expect_eq(s:readByte(), 255, "byte written as -1")
    expect_eq(s:readNumber(), -2, "number")
    expect_eq(s:readNumber(), -1, "unsigned number reads back signed")
    expect_eq(s:readFloat(), 1.5, "float")
    expect_eq(s:readString(), "hi", "string")
    expect_eq(s.remaining, 0, "remaining")
    expect_eq(tostring(s), "Stream(18 bytes)", "tostring")
end)

test("v1's byte layout: little-endian numbers, big-endian string length", function()
    local s = Stream.new()
    s:writeNumber(0x01020304)
    s:writeString("ab")
    s:send(p)
    expect_call("SendClientScriptData(0, 0403020100026162, 8)")
end)

test("reads beyond the data raise errors instead of reading garbage", function()
    local s = Stream()
    s:writeByte(1)
    s:writeByte(2)
    s:writeByte(3)
    expect_error("Stream: not enough data to read a number (3 of 4 bytes left)", function() s:readNumber() end)
    expect_eq(s:readByte(), 1, "a failed read consumes nothing")
    s:clear()
    expect_eq(s.size, 0, "cleared")
    expect_error("not enough data to read a byte", function() s:readByte() end)
    s:writeByte(0)
    s:writeByte(10)
    s:writeByte(65)
    expect_error("not enough data to read a string of 10 bytes", function() s:readString() end)
end)

test("writes stop at 4096 bytes", function()
    local s = Stream()
    s:writeString(string.rep("x", 4094))
    expect_eq(s.size, 4096, "full")
    expect_error("Stream: no room to write a byte (4096 of 4096 bytes used)", function() s:writeByte(1) end)
    s:clear()
    s:writeString(string.rep("x", 4093))
    expect_error("no room to write a string", function() s:writeString("ab") end)
    expect_eq(s.size, 4095, "a failed write writes nothing")
    s:clear()
    expect_error("at most 65535 bytes", function() s:writeString(string.rep("x", 70000)) end)
end)

test("argument checks", function()
    local s = Stream()
    expect_error("bad argument #1 to 'writeByte' (value 256 out of range [-128, 255])",
        function() s:writeByte(256) end)
    expect_error("bad argument #1 to 'writeNumber' (number has no integer representation)",
        function() s:writeNumber(1.5) end)
    expect_error("bad argument #1 to 'writeString' (string expected, got nil)",
        function() s:writeString(nil) end)
end)

test("send to everyone", function()
    local q = fake.connect("Bob")
    local s = Stream()
    s:writeByte(7)
    s:send()
    expect_calls({ "SendClientScriptData(0, 07, 1)", "SendClientScriptData(" .. q.id .. ", 07, 1)" })
    fake.disconnect(q.id)
end)
