# Embeds a file in the plugin as a byte array.
#
#   vcmp_lua_embed_file(<output.cpp> <file> <function>)
#
# The generated file defines
#   std::span<const unsigned char> vcmp_lua::embedded::<function>() noexcept
# (declare it where it is used). The array holds the file's bytes only, with
# no terminating NUL.

if(CMAKE_SCRIPT_MODE_FILE)
    # Script mode, run at build time: -DINPUT=<file> -DOUTPUT=<file.cpp> -DFUNCTION=<name>
    file(READ "${INPUT}" hex HEX)
    if(hex STREQUAL "")
        message(FATAL_ERROR "EmbedFile: ${INPUT} is empty")
    endif()
    string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n" bytes "${bytes}")
    file(WRITE "${OUTPUT}.tmp"
"// Generated by cmake/EmbedFile.cmake from ${INPUT}. Do not edit.
#include <span>

namespace vcmp_lua::embedded {
namespace {

const unsigned char kData[] = {
${bytes}
};

}  // namespace

std::span<const unsigned char> ${FUNCTION}() noexcept { return kData; }

}  // namespace vcmp_lua::embedded
")
    file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
    file(REMOVE "${OUTPUT}.tmp")
    return()
endif()

set(_VCMP_LUA_EMBED_FILE_SCRIPT "${CMAKE_CURRENT_LIST_FILE}")

function(vcmp_lua_embed_file output input function)
    add_custom_command(
        OUTPUT "${output}"
        COMMAND "${CMAKE_COMMAND}" "-DINPUT=${input}" "-DOUTPUT=${output}" "-DFUNCTION=${function}"
                -P "${_VCMP_LUA_EMBED_FILE_SCRIPT}"
        DEPENDS "${input}" "${_VCMP_LUA_EMBED_FILE_SCRIPT}"
        COMMENT "Embedding ${input}"
        VERBATIM)
endfunction()
