# Embeds pure-Lua modules in the plugin as byte arrays, so `require` finds them
# without any file on disk (plan B6). The runtime loads them in text mode, so
# precompiled bytecode is rejected here.
#
#   vcmp_lua_embed(<output.cpp> MODULES <module.name> <file.lua> [...])
#
# The generated file defines vcmp_lua::embedded::Modules() (src/runtime/embedded.hpp).

if(CMAKE_SCRIPT_MODE_FILE)
    # Script mode, run at build time: -DMANIFEST=<manifest.cmake> -DOUTPUT=<file.cpp>
    include("${MANIFEST}")
    set(arrays "")
    set(entries "")
    set(index 0)
    foreach(name file IN ZIP_LISTS EMBED_NAMES EMBED_FILES)
        file(READ "${file}" hex HEX)
        if(hex STREQUAL "")
            message(FATAL_ERROR "EmbedLua: ${file} is empty")
        endif()
        if(hex MATCHES "^1b4c7561")
            message(FATAL_ERROR "EmbedLua: ${file} is precompiled bytecode")
        endif()
        string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
        string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n" bytes "${bytes}")
        string(APPEND arrays "// ${name}\nconst unsigned char kSource${index}[] = {\n${bytes}\n};\n\n")
        string(APPEND entries "    {\"${name}\", \"@builtin/${name}.lua\", kSource${index}, sizeof kSource${index}},\n")
        math(EXPR index "${index} + 1")
    endforeach()
    file(WRITE "${OUTPUT}.tmp"
"// Generated by cmake/EmbedLua.cmake. Do not edit.
#include \"runtime/embedded.hpp\"

namespace vcmp_lua::embedded {
namespace {

${arrays}constexpr Module kModules[] = {
${entries}};

}  // namespace

std::span<const Module> Modules() noexcept { return kModules; }

}  // namespace vcmp_lua::embedded
")
    file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
    file(REMOVE "${OUTPUT}.tmp")
    return()
endif()

set(_VCMP_LUA_EMBED_SCRIPT "${CMAKE_CURRENT_LIST_FILE}")

function(vcmp_lua_embed output)
    cmake_parse_arguments(PARSE_ARGV 1 arg "" "" "MODULES")
    list(LENGTH arg_MODULES count)
    math(EXPR remainder "${count} % 2")
    if(count EQUAL 0 OR NOT remainder EQUAL 0)
        message(FATAL_ERROR "vcmp_lua_embed: MODULES takes <module.name> <file.lua> pairs")
    endif()

    set(names "")
    set(files "")
    set(expect_name TRUE)
    foreach(item IN LISTS arg_MODULES)
        if(expect_name)
            if(item IN_LIST names)
                message(FATAL_ERROR "vcmp_lua_embed: module '${item}' is listed twice")
            endif()
            list(APPEND names "${item}")
            set(expect_name FALSE)
        else()
            if(NOT EXISTS "${item}")
                message(FATAL_ERROR "vcmp_lua_embed: ${item} does not exist")
            endif()
            list(APPEND files "${item}")
            set(expect_name TRUE)
        endif()
    endforeach()

    set(manifest "${output}.manifest.cmake")
    file(CONFIGURE OUTPUT "${manifest}"
        CONTENT "set(EMBED_NAMES [==[${names}]==])\nset(EMBED_FILES [==[${files}]==])\n")
    list(LENGTH names module_count)
    add_custom_command(
        OUTPUT "${output}"
        COMMAND "${CMAKE_COMMAND}" "-DMANIFEST=${manifest}" "-DOUTPUT=${output}"
                -P "${_VCMP_LUA_EMBED_SCRIPT}"
        DEPENDS ${files} "${manifest}" "${_VCMP_LUA_EMBED_SCRIPT}"
        COMMENT "Embedding ${module_count} Lua modules"
        VERBATIM)
endfunction()
